dpc-sdp/tide_media

Makefile
config/install/field.field.media.document.field_media_file.yml
config/install/field.field.media.file.field_media_file.yml
tests/behat/features/fields.feature

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-1002
Content PR: https://github.com/dpc-sdp/content-vic-gov-au/pull/339
1.  Update configuration to enable upload zip, tiff and eps files
2. Update behat test to enable test new extensions

[SDPA-1002] Update document to upload zip, tiff and eps files

---

composer.json
tests/behat/features/fields.feature

JIRA: https://digital-engagement.atlassian.net/browse/SDPA-1213
Related PRs:
* Tide Core: https://github.com/dpc-sdp/tide_core/pull/57
* Tide Media: https://github.com/dpc-sdp/tide_media/pull/19
* Tide API: https://github.com/dpc-sdp/tide_api/pull/28
* Tide Site: https://github.com/dpc-sdp/tide_site/pull/18
* Tide Webform: https://github.com/dpc-sdp/tide_webform/pull/21
* Tide News: https://github.com/dpc-sdp/tide_news/pull/14
* Tide Page: https://github.com/dpc-sdp/tide_page/pull/14
* Tide Event: https://github.com/dpc-sdp/tide_event/pull/24
* Tide Landing Page: https://github.com/dpc-sdp/tide_landing_page/pull/63
* Tide Monsido: https://github.com/dpc-sdp/tide_monsido/pull/13
* Tide Search: https://github.com/dpc-sdp/tide_search/pull/11
* Tide: https://github.com/dpc-sdp/tide/pull/39
* …

[SDPA-1213] Upgraded to new Tide Core with upgraded Metatag.

---

composer.json

On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>

Release 1.2.4.

---

config/install/core.entity_view_display.media.audio.default.yml
config/install/core.entity_view_display.media.embedded_video.default.yml
config/install/core.entity_view_display.media.video.default.yml
config/install/field.field.media.audio.field_media_transcript.yml
config/install/field.field.media.embedded_video.field_media_transcript.yml
config/install/field.field.media.video.field_media_transcript.yml
config/install/field.storage.media.field_media_transcript.yml
tide_media.install

https://digital-engagement.atlassian.net/browse/SDPA-2449

[SDPA-2449] change string long to text long

---

composer.json
config/install/core.entity_form_display.paragraph.call_to_action_image.default.yml
config/install/core.entity_view_display.paragraph.call_to_action_image.default.yml
config/install/field.field.paragraph.call_to_action_image.field_paragraph_cta.yml
config/install/field.field.paragraph.call_to_action_image.field_paragraph_media.yml
config/install/field.storage.paragraph.field_paragraph_media.yml
config/install/paragraphs.paragraphs_type.call_to_action_image.yml
config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--call_to_action_image.yml
tide_media.info.yml

JIRA:
* https://digital-engagement.atlassian.net/browse/SDPA-2391
* https://digital-engagement.atlassian.net/browse/SDPA-2565
Tide Core: https://github.com/dpc-sdp/tide_core/pull/77

Attempted to fix interdependencies.

---

tests/behat/features/fields.feature
tide_media.install

Jira issue: https://digital-engagement.atlassian.net/browse/SDPA-2673
1. added a hook_update to enable the field in form_display of all media bundles.
relates to https://github.com/dpc-sdp/content-vic-gov-au/pull/720
latest comment: https://github.com/dpc-sdp/content-vic-gov-au/pull/720#issuecomment-541497712

SDPA-2673 updated dependencies

---

composer.json
config/install/views.view.tide_media_browser.yml
tide_media.install

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-3151
1.  Changed the tide media image_search name filter operator from '=' to contain.

[SDPA-3151] Changed the tide media image_search name filter operator from '=' to contain.

---

composer.json
config/install/field.storage.node.field_node_timeline.yml
dev-tools.sh
tide_media.info.yml

1. Added field.storage.node.field_node_timeline - not previsouly captured in a Tide module.
dpc-sdp/content-vic-gov-au#724
dpc-sdp/tide_grant#1

Config updates as part of dpc-sdp module separation

---

tests/behat/features/fields.feature

https://digital-engagement.atlassian.net/browse/SDPA-3802
1. Updated test scenario.

[SDPA-3802] Test scenario updated.

---

composer.json

ttps://digital-engagement.atlassian.net/browse/SDPA-4030
1. update svg_image module based on [sa-contrib-2020-008](https://www.drupal.org/sa-contrib-2020-008) reason.
https://github.com/dpc-sdp/content-vic-gov-au/pull/829

[SDPA-4030] update svg_image module

---

tide_media.install

https://digital-engagement.atlassian.net/browse/SW-86
entity browser settings should get updated.

[SW-86] clean up entity browsers

---

tide_media.install

we need hook_update_12 to run but it ran already.
1. Fills hook_update_12 with code that had been ran.
2. Increases currently hook_update_12 to 13

Increases hook_update_N to 13 and Fills hook_update_12

---

tide_media.install

https://digital-engagement.atlassian.net/browse/SDPA-4510
refactor `tide_media_update_8013`

[SDPA-4510] fixes tide_media_update_8013 issue

---

tide_media.module

On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>

Fixed PHP warnings when using media browser with images.

---

tide_media.module

**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPA-5781
1. Added embedded with transcript as a default view mode for audio and embedded video media entities.

Added embedded with transcript as default value for embedded video and audio.

---

tide_media.module

https://digital-engagement.atlassian.net/browse/SDPA-5945
1) Added "title" for embedded video

[SDPA-5946 Add title tag for embedded video.

---

composer.json
config/install/core.entity_form_display.paragraph.timeline.default.yml
config/install/core.entity_view_display.paragraph.timeline.default.yml
config/install/field.field.paragraph.timeline.field_current_milestone.yml
config/install/field.field.paragraph.timeline.field_paragraph_title.yml
config/optional/jsonapi_extras.jsonapi_resource_config.paragraph--timeline.yml
src/Validate/Timelines.php
tide_media.install
tide_media.module

https://digital-engagement.atlassian.net/browse/SDPA-5874
1. Added a new "Current milestone" checkbox for "timeline" component which is a component under "timeline" component. (One "timelines" component can have multiple "timeline" component)
2. Added custom validation for the "timelines" component where it will check there is only one "Current milestone" checkbox is checked among the multiple "timeline" components.
3. Added update hook to create the new check field for the existing projects.
https://github.com/dpc-sdp/tide_core/pull/318 (This is where the new field's storage is placed)
https://github.com/dpc-sdp/tide_grant/pull/17 (Updated the component for tide_grant)

[SDPA-5874] Added timeline component new field and display settings.

---

composer.json
dev-tools.sh
tide_media.install

**Jira:**
https://digital-vic.atlassian.net/browse/SRM-512
https://digital-vic.atlassian.net/browse/SDPAP-6730
**Changes**
1. Remove deprecated `drupal_get_path()` function

[SRM-512] SDPAP-6730 Remove deprecated "drupal_get_path()"

---

composer.json

Patch got fixed in the new release and causing issues for the modules and dependency modules to build, because it cannot apply the patch anymore.
- https://www.drupal.org/project/entity_usage/issues/3098733
Removed the patch, as the module is not locked, during build and composer update it will always get the latest version which has the patch fix.

Removed entity usage patch that is fixed in the new module release.

---

js/embed_media_back_button.js

Fixes missing Previous button in media browser

Fixes missing Previous button in media browser.

---

composer.json
patches/video_embed_field/video_embed_field_6.patch

Using a noncanonical repository (fork) that originates from a Drupal ticket for issue resolution can potentially lead to a broken composer. This may happen if the changes are merged into the main branch and the forked repository is subsequently closed and deleted.

Remove noncanonical repo(video_embed_field)

---

tests/behat/features/license_types.feature
tide_media.install

https://digital-vic.atlassian.net/browse/SDPAP-8411
Update the module to add default `License types` terms.

[SDPAP-8411] Adds default License types
